export const TURN_ANIMATION_DURATION = 160;
export const MERGER_IN_ANIMATION_DURATION = TURN_ANIMATION_DURATION / 5;
export const MERGER_OUT_ANIMATION_DURATION = TURN_ANIMATION_DURATION / 5;
export const MERGE_START_PERCENTAGE = 10;
